# Generated by Django 3.2.9 on 2021-12-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField(default='[]')),
                ('image', models.OneToOneField(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='idealfinder.imageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=20)),
                ('image', models.OneToOneField(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='idealfinder.imageinfo')),
            ],
        ),
    ]
